# Generated by Django 2.2.2 on 2019-11-08 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micky', '0002_auto_20191108_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='price',
        ),
    ]
